// Mocks generated by Mockito 5.4.5 from annotations
// in wird2/test/settings_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:flutter/foundation.dart' as _i3;
import 'package:flutter_bloc/flutter_bloc.dart' as _i20;
import 'package:flutter_local_notifications/src/flutter_local_notifications_plugin.dart'
    as _i6;
import 'package:flutter_local_notifications/src/initialization_settings.dart'
    as _i8;
import 'package:flutter_local_notifications/src/notification_details.dart'
    as _i10;
import 'package:flutter_local_notifications/src/platform_specifics/android/schedule_mode.dart'
    as _i13;
import 'package:flutter_local_notifications/src/platform_specifics/ios/enums.dart'
    as _i12;
import 'package:flutter_local_notifications/src/types.dart' as _i14;
import 'package:flutter_local_notifications_platform_interface/flutter_local_notifications_platform_interface.dart'
    as _i9;
import 'package:hive_flutter/hive_flutter.dart' as _i16;
import 'package:mockito/mockito.dart' as _i1;
import 'package:timezone/timezone.dart' as _i11;
import 'package:wird2/core/repositories/sunnah_repository.dart' as _i19;
import 'package:wird2/core/services/storage_service.dart' as _i15;
import 'package:wird2/features/home/bloc/prayer_bloc.dart' as _i5;
import 'package:wird2/models/prayer.dart' as _i18;
import 'package:wird2/models/prayer_log.dart' as _i17;
import 'package:wird2/models/settings.dart' as _i2;
import 'package:wird2/models/sunnah.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAppSettings_0 extends _i1.SmartFake implements _i2.AppSettings {
  _FakeAppSettings_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeValueListenable_1<T> extends _i1.SmartFake
    implements _i3.ValueListenable<T> {
  _FakeValueListenable_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreakData_2 extends _i1.SmartFake implements _i2.StreakData {
  _FakeStreakData_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSunnah_3 extends _i1.SmartFake implements _i4.Sunnah {
  _FakeSunnah_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePrayerState_4 extends _i1.SmartFake implements _i5.PrayerState {
  _FakePrayerState_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FlutterLocalNotificationsPlugin].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterLocalNotificationsPlugin extends _i1.Mock
    implements _i6.FlutterLocalNotificationsPlugin {
  MockFlutterLocalNotificationsPlugin() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<bool?> initialize(
    _i8.InitializationSettings? initializationSettings, {
    _i9.DidReceiveNotificationResponseCallback?
        onDidReceiveNotificationResponse,
    _i9.DidReceiveBackgroundNotificationResponseCallback?
        onDidReceiveBackgroundNotificationResponse,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [initializationSettings],
          {
            #onDidReceiveNotificationResponse: onDidReceiveNotificationResponse,
            #onDidReceiveBackgroundNotificationResponse:
                onDidReceiveBackgroundNotificationResponse,
          },
        ),
        returnValue: _i7.Future<bool?>.value(),
      ) as _i7.Future<bool?>);

  @override
  _i7.Future<_i9.NotificationAppLaunchDetails?>
      getNotificationAppLaunchDetails() => (super.noSuchMethod(
            Invocation.method(
              #getNotificationAppLaunchDetails,
              [],
            ),
            returnValue: _i7.Future<_i9.NotificationAppLaunchDetails?>.value(),
          ) as _i7.Future<_i9.NotificationAppLaunchDetails?>);

  @override
  _i7.Future<void> show(
    int? id,
    String? title,
    String? body,
    _i10.NotificationDetails? notificationDetails, {
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #show,
          [
            id,
            title,
            body,
            notificationDetails,
          ],
          {#payload: payload},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> cancel(
    int? id, {
    String? tag,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancel,
          [id],
          {#tag: tag},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> cancelAll() => (super.noSuchMethod(
        Invocation.method(
          #cancelAll,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> zonedSchedule(
    int? id,
    String? title,
    String? body,
    _i11.TZDateTime? scheduledDate,
    _i10.NotificationDetails? notificationDetails, {
    required _i12.UILocalNotificationDateInterpretation?
        uiLocalNotificationDateInterpretation,
    bool? androidAllowWhileIdle = false,
    _i13.AndroidScheduleMode? androidScheduleMode,
    String? payload,
    _i14.DateTimeComponents? matchDateTimeComponents,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #zonedSchedule,
          [
            id,
            title,
            body,
            scheduledDate,
            notificationDetails,
          ],
          {
            #uiLocalNotificationDateInterpretation:
                uiLocalNotificationDateInterpretation,
            #androidAllowWhileIdle: androidAllowWhileIdle,
            #androidScheduleMode: androidScheduleMode,
            #payload: payload,
            #matchDateTimeComponents: matchDateTimeComponents,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> periodicallyShow(
    int? id,
    String? title,
    String? body,
    _i9.RepeatInterval? repeatInterval,
    _i10.NotificationDetails? notificationDetails, {
    String? payload,
    bool? androidAllowWhileIdle = false,
    _i13.AndroidScheduleMode? androidScheduleMode,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #periodicallyShow,
          [
            id,
            title,
            body,
            repeatInterval,
            notificationDetails,
          ],
          {
            #payload: payload,
            #androidAllowWhileIdle: androidAllowWhileIdle,
            #androidScheduleMode: androidScheduleMode,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> periodicallyShowWithDuration(
    int? id,
    String? title,
    String? body,
    Duration? repeatDurationInterval,
    _i10.NotificationDetails? notificationDetails, {
    _i13.AndroidScheduleMode? androidScheduleMode =
        _i13.AndroidScheduleMode.exact,
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #periodicallyShowWithDuration,
          [
            id,
            title,
            body,
            repeatDurationInterval,
            notificationDetails,
          ],
          {
            #androidScheduleMode: androidScheduleMode,
            #payload: payload,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i9.PendingNotificationRequest>>
      pendingNotificationRequests() => (super.noSuchMethod(
            Invocation.method(
              #pendingNotificationRequests,
              [],
            ),
            returnValue: _i7.Future<List<_i9.PendingNotificationRequest>>.value(
                <_i9.PendingNotificationRequest>[]),
          ) as _i7.Future<List<_i9.PendingNotificationRequest>>);

  @override
  _i7.Future<List<_i9.ActiveNotification>> getActiveNotifications() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveNotifications,
          [],
        ),
        returnValue: _i7.Future<List<_i9.ActiveNotification>>.value(
            <_i9.ActiveNotification>[]),
      ) as _i7.Future<List<_i9.ActiveNotification>>);
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i15.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i7.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i2.AppSettings getSettings() => (super.noSuchMethod(
        Invocation.method(
          #getSettings,
          [],
        ),
        returnValue: _FakeAppSettings_0(
          this,
          Invocation.method(
            #getSettings,
            [],
          ),
        ),
      ) as _i2.AppSettings);

  @override
  _i7.Future<void> saveSettings(_i2.AppSettings? settings) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSettings,
          [settings],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i3.ValueListenable<_i16.Box<_i2.AppSettings>> getSettingsListenable() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSettingsListenable,
          [],
        ),
        returnValue: _FakeValueListenable_1<_i16.Box<_i2.AppSettings>>(
          this,
          Invocation.method(
            #getSettingsListenable,
            [],
          ),
        ),
      ) as _i3.ValueListenable<_i16.Box<_i2.AppSettings>>);

  @override
  _i7.Future<void> updateSetting<T>(T Function(_i2.AppSettings)? update) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSetting,
          [update],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  bool isOnboardingCompleted() => (super.noSuchMethod(
        Invocation.method(
          #isOnboardingCompleted,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i7.Future<void> completeOnboarding() => (super.noSuchMethod(
        Invocation.method(
          #completeOnboarding,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i17.PrayerLog? getPrayerLog(DateTime? date) =>
      (super.noSuchMethod(Invocation.method(
        #getPrayerLog,
        [date],
      )) as _i17.PrayerLog?);

  @override
  _i7.Future<void> savePrayerLog(_i17.PrayerLog? log) => (super.noSuchMethod(
        Invocation.method(
          #savePrayerLog,
          [log],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updatePrayerEntry(
    _i18.Prayer? prayer,
    _i17.PrayerEntry? entry,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePrayerEntry,
          [
            prayer,
            entry,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  List<_i17.PrayerLog> getPrayerLogsForRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPrayerLogsForRange,
          [
            start,
            end,
          ],
        ),
        returnValue: <_i17.PrayerLog>[],
      ) as List<_i17.PrayerLog>);

  @override
  List<_i17.PrayerLog> getRecentPrayerLogs(int? days) => (super.noSuchMethod(
        Invocation.method(
          #getRecentPrayerLogs,
          [days],
        ),
        returnValue: <_i17.PrayerLog>[],
      ) as List<_i17.PrayerLog>);

  @override
  _i7.Future<void> deletePrayerLog(DateTime? date) => (super.noSuchMethod(
        Invocation.method(
          #deletePrayerLog,
          [date],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> clearAllPrayerLogs() => (super.noSuchMethod(
        Invocation.method(
          #clearAllPrayerLogs,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i2.StreakData getStreakData() => (super.noSuchMethod(
        Invocation.method(
          #getStreakData,
          [],
        ),
        returnValue: _FakeStreakData_2(
          this,
          Invocation.method(
            #getStreakData,
            [],
          ),
        ),
      ) as _i2.StreakData);

  @override
  _i7.Future<void> saveStreakData(_i2.StreakData? data) => (super.noSuchMethod(
        Invocation.method(
          #saveStreakData,
          [data],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateStreak({
    required bool? isPerfectDay,
    required Map<_i18.Prayer, bool>? prayerOnTime,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStreak,
          [],
          {
            #isPerfectDay: isPerfectDay,
            #prayerOnTime: prayerOnTime,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> resetStreak() => (super.noSuchMethod(
        Invocation.method(
          #resetStreak,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> clearAllData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  Map<String, int> getStorageStats() => (super.noSuchMethod(
        Invocation.method(
          #getStorageStats,
          [],
        ),
        returnValue: <String, int>{},
      ) as Map<String, int>);
}

/// A class which mocks [SunnahRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSunnahRepository extends _i1.Mock implements _i19.SunnahRepository {
  MockSunnahRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i4.Sunnah>> getAllSunnahs() => (super.noSuchMethod(
        Invocation.method(
          #getAllSunnahs,
          [],
        ),
        returnValue: _i7.Future<List<_i4.Sunnah>>.value(<_i4.Sunnah>[]),
      ) as _i7.Future<List<_i4.Sunnah>>);

  @override
  List<_i4.Sunnah> getAllSunnahsSync() => (super.noSuchMethod(
        Invocation.method(
          #getAllSunnahsSync,
          [],
        ),
        returnValue: <_i4.Sunnah>[],
      ) as List<_i4.Sunnah>);

  @override
  _i7.Future<_i4.Sunnah?> getSunnahById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getSunnahById,
          [id],
        ),
        returnValue: _i7.Future<_i4.Sunnah?>.value(),
      ) as _i7.Future<_i4.Sunnah?>);

  @override
  _i7.Future<_i4.Sunnah> getWeeklySunnah() => (super.noSuchMethod(
        Invocation.method(
          #getWeeklySunnah,
          [],
        ),
        returnValue: _i7.Future<_i4.Sunnah>.value(_FakeSunnah_3(
          this,
          Invocation.method(
            #getWeeklySunnah,
            [],
          ),
        )),
      ) as _i7.Future<_i4.Sunnah>);

  @override
  _i7.Future<_i4.Sunnah> skipWeeklySunnah() => (super.noSuchMethod(
        Invocation.method(
          #skipWeeklySunnah,
          [],
        ),
        returnValue: _i7.Future<_i4.Sunnah>.value(_FakeSunnah_3(
          this,
          Invocation.method(
            #skipWeeklySunnah,
            [],
          ),
        )),
      ) as _i7.Future<_i4.Sunnah>);
}

/// A class which mocks [PrayerBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockPrayerBloc extends _i1.Mock implements _i5.PrayerBloc {
  MockPrayerBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.PrayerState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakePrayerState_4(
          this,
          Invocation.getter(#state),
        ),
      ) as _i5.PrayerState);

  @override
  _i7.Stream<_i5.PrayerState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i7.Stream<_i5.PrayerState>.empty(),
      ) as _i7.Stream<_i5.PrayerState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  _i7.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void add(_i5.PrayerEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i5.PrayerEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i5.PrayerState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i5.PrayerEvent>(
    _i20.EventHandler<E, _i5.PrayerState>? handler, {
    _i20.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i20.Transition<_i5.PrayerEvent, _i5.PrayerState>? transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i20.Change<_i5.PrayerState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
